---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: mpaivabarbosa/molecule-systemd-centos:8
    pre_build_image: true
    privileged: true
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
    - destroy
    - create
    - converge
    - destroy
