---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos8-ansible
    image: mpaivabarbosa/molecule-systemd-centos:8
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro    
    privileged: true
    pre_build_image: true 
    override_command: false  
  - name: ubuntu-ansible
    image: mpaivabarbosa/molecule-systemd-ubuntu:22.04 
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true   
    override_command: false
  - name: debian-ansible
    image: mpaivabarbosa/molecule-systemd-debian:10  
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro 
    privileged: true
    pre_build_image: true     
    override_command: false 
provisioner:
  name: ansible
verifier:
  name: ansible
